/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Atxy2k.CustomTextField.RestrictedTextField;
import static Interfaz.Consulta.SQL_PASSWORD;
import static Interfaz.Consulta.SQL_USERNAME;
import static Interfaz.Consulta.URL;
import static Interfaz.Consulta.getConection;
import com.sun.org.apache.bcel.internal.generic.RETURN;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 * User login module
 * 
 * @since 1.0.0
 * @author David Rivas
 */
public class Login extends javax.swing.JFrame {
    private Component confirmation;

    /**
     *The URL of the server you want to access is saved
     */
    public static final String URL = "jdbc:mysql://localhost:3306/troxxy";

    /**
     *The username is saved in the database
     */
    public static final String SQL_USERNAME = "root";

    /**
     *The database password is saved
     */
    public static final String SQL_PASSWORD = "";
    private String user, pass;
    /**
     * Variables are prepared to reduce the code to write
     */
    PreparedStatement PS = null;
    ResultSet RS = null;
    
    /**
     *Methods and variables necessary for the operation of the code were placed
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtUser.setFocusable(true);
    }
    
     /**
     * Code used to establish the connection with the database
     * @return the connection established
     */
    public static Connection getConection() {
        
        Connection con = null;
        
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection(URL, SQL_USERNAME, SQL_PASSWORD);
        } catch (ClassNotFoundException | SQLException e){
            System.err.println("Error: "+e);
        }
        return con;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, -1));
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 180, -1));

        jButton1.setText("Inicio de sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 194, 117, 40));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 194, 117, 40));

        jLabel2.setText("Contraseña: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 20));

        jLabel3.setText("Usuario: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gray.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);// Button to close the tab
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed
/**
     *Code whose purpose is to restrict and validate the input fields
     */
    public void ValidacionDeCampos(){
        /*Text field validation for user */
        RestrictedTextField a = new RestrictedTextField(txtUser);
        a.setLimit(8);
        
        /*Validation of text field for password*/
        RestrictedTextField b = new RestrictedTextField(txtPass);
        b.setLimit(8);
        
    }
    /**Button that activates the search of the data referring to the user
     * together with a series of conditions that will allow to give way or
     * stop the user who tries to enter
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = null;
        
        try {
            con = getConection();
            
            PS = con.prepareStatement("SELECT * FROM users ORDER BY id ASC");
            RS = PS.executeQuery();
            while(RS.next())
            {
            user = RS.getString("Usuario");
            pass = RS.getString("Contraseña");
            }
            
            if(user.equals(txtUser.getText()) && pass.equals(txtPass.getText())){
            JOptionPane.showMessageDialog(this, "Bienvenido " + user +"!");
            /**
             * Code to send the user from this screen to the query screen
             */
            this.setVisible(false);
            Consulta a = new Consulta();
            a.setVisible(true);
            
            }else if(txtUser.getText().isEmpty() && txtPass.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Campos Usuario y contraseña Vacios");
            txtUser.setFocusable(true);
            
            }else if(txtUser.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Campo Usuario Vacio");
            txtUser.setFocusable(true);
            
            }else if(txtPass.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Campo Contraseña Vacio");
            txtPass.setFocusable(true);
            
            }else if(txtUser.getText().compareTo(user)!=0 && txtPass.getText().compareTo(pass)!=0){
            JOptionPane.showMessageDialog(this, "Usuario y/o contraseña invalidos");
            txtUser.setFocusable(true);
            
            }else if(txtUser.getText().compareTo(user)!=0 ){
            JOptionPane.showMessageDialog(this, "Usuario invalido");
            txtUser.setFocusable(true);
            
            }else if(txtPass.getText().compareTo(pass)!=0){
            JOptionPane.showMessageDialog(this, "Contraseña invalida");
            txtPass.setFocusable(true);
            }
            PS.close();
        } catch (SQLException e) {
            System.out.println("Error al visualizar los datos: "+e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
